# NOTE: update this with your service name
service: Projectland-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  authenticateUser:
    handler: handler.authenticateUser
    events:
      - http:
          path: /profile
          method: get
          cors: true
      - cognitoUserPool:
          pool: Projectland User Pool
          trigger: PreSignUp

# resources:
#   Resources: 
#     usersTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: users
#         AttributeDefinitions:
#           - AttributeName: name
#             AttributeType: S
#         KeySchema:
#           - AttributeName: name
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1    
