service: projectland-auth

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2

functions:
  clearCachedSession:
    handler: handler.clearCachedSession
  generateLoginEvent:
    handler: handler.generateLoginEvent
